### ISSUE TITLE
dbs.Delete()

### ISSUE THREAD

**Issue by thee-engineer** [thee-engineer/astonhack-2016#1]
When trying to run 'testCrate.py' or 'geesemanager.py', the program returns the following error:

```sql
Traceback (most recent call last):
  File "source/geesemanager.py", line 164, in <module>
    dbs.Delete()
  File "/fwgsim/source/db/database.py", line 90, in Delete
    """)
  File "/usr/lib/python2.7/site-packages/crate/client/cursor.py", line 54, in execute
    bulk_parameters)
  File "/usr/lib/python2.7/site-packages/crate/client/http.py", line 304, in sql
    content = self._json_request('POST', self.path, data=data)
  File "/usr/lib/python2.7/site-packages/crate/client/http.py", line 416, in _json_request
    _raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/crate/client/http.py", line 170, in _raise_for_status
    error_trace=error_trace)
crate.client.exceptions.ProgrammingError: SQLActionException[SchemaUnknownException: Schema 'doc' unknown]
``` 
Do you know what causes it? @Friteee

**Comment by Friteee** [comment]
My guess is that script tries to delete a table which isn't there.

**Comment by Friteee** [comment]
Try removing the call for delete function and see if it helps the problem

**Comment by thee-engineer** [comment]
Ok, I am compiling now the docker image.
